sudo: false
language: python
python:
  - '2.7'
  - '3.5'
  - 'pypy'
before_install:
  - git submodule update --init
install:
  - pip install tox
script:
  - tools/run_tests/run_tests.py -l python --travis
notifications:
  email:
    recipients:
      - vcamx3@gmail.com
    on_success: always
    on_failure: always
